app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime


class User(UserMixin, db.Model):
    '''
        News class to define User Objects
        '''
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pass_secure = db.Column(db.String(255))


    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.pass_secure, password)

    def __repr__(self):
        return f'User {self.username, self.password, self.email}'

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))


class Pitch(db.Model):

    __tablename__ = 'pitches'

    id = db.Column(db.Integer,primary_key = True)
    pitch_id = db.Column(db.Integer)
    pitch_title = db.Column(db.String)
    pitch_category= db.Column(db.String)
    pitch_prose = db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitch(cls, id):
        pitch = Pitch.query.filter_by(pitch_id=id).all()
        return pitch

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField, TextAreaField
from wtforms.validators import Required


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[Required()])
    password = StringField('Password', validators=[Required()])
    submit = SubmitField('Submit')


class RegisterForm(FlaskForm):
    email = StringField('Email', validators=[Required()])
    username = StringField('Username', validators=[Required()])
    password = StringField('Password', validators=[Required()])
    submit = SubmitField('Submit')


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

class PitchForm(FlaskForm):
    pitch_title = StringField('Pitch Title', validators=[Required()])
    pitch_category = StringField('Category', validators=[Required()])
    pitch_prose = TextAreaField('Pitch', validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail



bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos = UploadSet('photos',IMAGES)
mail = Mail()


def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Registering blueprints
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/authenticate')

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    # configure UploadSet
    configure_uploads(app, photos)


    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from ..models import User
from.forms import UpdateProfile
from flask_login import login_required, current_user
from .. import db, photos


# Views
@main.route('/')
def index():

    '''
    View page function that returns the index page and its data
    '''
    title = 'Pitch Perfect'

    return render_template('index.html', title=title)


@main.route('/user/')
def profile():
    user = User.query.filter_by(username = current_user.username).first()
    # all = Pitch.query.all()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user, all =all)


@main.route('/user/update',methods = ['GET','POST'])
@login_required
def update_profile():
    user = User.query.filter_by(username = current_user.username).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('main.profile',uname=user.username))

    return render_template('profile/update.html',form =form)


@main.route('/category/business',methods = ['GET','POST'])
@login_required
def business():
    user = User.query.filter_by(username = current_user.username).first()

    if user is None:
        abort(404)

    return render_template("category/business.html", user = user)


@main.route('/category/entertainment',methods = ['GET','POST'])
@login_required
def entertainment():
    user = User.query.filter_by(username = current_user.username).first()

    if user is None:
        abort(404)

    return render_template("category/entertainment.html", user = user)


@main.route('/category/school',methods = ['GET','POST'])
@login_required
def school():
    user = User.query.filter_by(username = current_user.username).first()

    if user is None:
        abort(404)

    return render_template("category/school.html", user = user)


@main.route('/user/update/pic',methods= ['POST'])
@login_required
def update_pic():
    user = User.query.filter_by(username = current_user.username).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=current_user.username))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% import 'bootstrap/wtf.html' as wtf %}
    {% if title %}
    <title> {{ title }}</title>
    {% else %}
    <title> Pitch Perfect </title>
    {% endif %}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    <meta charset="UTF-8">
    <link rel="shortcut icon" type="image/x-icon" href="https://lh3.googleusercontent.com/lbkd0aAnKL1AL0tyIXSdgQKNe5mGO7w3DXJDONY35pF2qsm1tJOpZF5N2P7_kxXPYg=w300-rw" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>
<body style="font-family:  sans-serif">
<div class="w3-bar w3-black w3-card">
  <a href="{{url_for('main.index')}}" class="w3-bar-item w3-button w3-mobile w3-green">Home</a>
    {% if current_user.is_authenticated %}
  <a href="{{url_for('auth.logout')}}" class="w3-bar-item w3-button w3-mobile">Log Out</a>
    {% else %}
  <a href="{{url_for('auth.login')}}" class="w3-bar-item w3-button w3-mobile">Log In</a>
    {%endif%}
    {% if current_user.is_authenticated %}
  <div class="w3-dropdown-hover w3-mobile">
    <button class="w3-button">Categories<i class="fa fa-caret-down"></i></button>
    <div class="w3-dropdown-content w3-bar-block w3-dark-grey">
      <a href="{{url_for('main.business')}}" class="w3-bar-item w3-button w3-mobile">Business</a>
      <a href="{{url_for('main.entertainment')}}" class="w3-bar-item w3-button w3-mobile">Entertainment</a>
      <a href="{{url_for('main.school')}}" class="w3-bar-item w3-button w3-mobile">School</a>
    </div>
      {%endif%}
  </div>

</div>


<div class="w3-container w3-grey" style="min-height:94vh">

{% block content %}

{% endblock%}
</div>

</body>
</html>

app/templates/category/business.html
{% extends 'base.html'%}

{% block content %}
<div class="w3-container w3-card w3-white w3-margin-bottom" style="height:100%">
    <h3 class="w3-center">Business Pitches</h3>
    <div class="w3-panel w3-green w3-card-4 w3-margin w3-padding">
      <h3>Consultation Pitch</h3>
        <hr>
        <p>I’ve spent a lot of time looking into the consulting industry and have reached out and spoken to four different alums in the consulting industry about their jobs and what it takes to be successful. Last semester, I did an independent project writing a business plan for an elder care non-profit that I’d had some exposure to through a neighbor, and the organization has begun to enact several of my recommendations. As this brief background illustrates, I enjoy analyzing key performance drivers, and have pursued academic and extra-curricular opportunities to develop skills in this area. I believe that I am a great fit for your organization and I would appreciate the opportunity to meet with you and learn more about your role at this company and discuss various prospects within the organization.</p>
    <div class="w3-bar w3-center">
        <i class="material-icons w3-button w3-margin">thumb_up</i> <i class="material-icons w3-button w3-margin">thumb_down</i>
    </div>
    </div>

    <div class="w3-panel w3-green w3-card-4 w3-margin w3-padding">
      <h3>Elevator Pitch</h3>
        <hr>
        <p>I’ve spent a lot of time looking into the consulting industry and talking to consultants about their jobs and what it takes to be successful. I believe my interests and skills are a good match for consulting. I have always liked solving problems. My major project during my internship last summer involved creating a questionnaire and conducting dozens of interviews of store operators to develop a best practices manual for franchise owners. I have a 3.7 GPA in Marketing at the University of Northern Colorado’s Monfort College of Business and have done very well in the more analytical courses I’ve taken, including Econometrics and Symbolic Logic. In those classes and others I’ve worked on teams, but I am also a member of the student council and have a good understanding of the importance of working with others to get the job done. I appreciate your willingness to introduce me to Jane Doe at (consulting firm). </p>
        <div class="w3-bar w3-center">
        <i class="material-icons w3-button w3-margin">thumb_up</i> <i class="material-icons w3-button w3-margin">thumb_down</i>
        </div>
    </div>
    <br>
</div>
{% endblock%}

app/templates/category/entertainment.html
{% extends 'base.html'%}

{% block content %}
<div class="w3-container w3-card w3-white w3-margin-bottom" style="height:100%">
    <h3 class="w3-center">Entertainment Pitches</h3>
    <div class="w3-panel w3-green w3-card-4 w3-margin w3-padding">
      <h3>Consultation Pitch</h3>
        <hr>
        <p>I’ve spent a lot of time looking into the consulting industry and have reached out and spoken to four different alums in the consulting industry about their jobs and what it takes to be successful. Last semester, I did an independent project writing a business plan for an elder care non-profit that I’d had some exposure to through a neighbor, and the organization has begun to enact several of my recommendations. As this brief background illustrates, I enjoy analyzing key performance drivers, and have pursued academic and extra-curricular opportunities to develop skills in this area. I believe that I am a great fit for your organization and I would appreciate the opportunity to meet with you and learn more about your role at this company and discuss various prospects within the organization.</p>
    <div class="w3-bar w3-center">
        <i class="material-icons w3-button w3-margin">thumb_up</i> <i class="material-icons w3-button w3-margin">thumb_down</i>
    </div>    </div>

    <div class="w3-panel w3-green w3-card-4 w3-margin w3-padding">
      <h3>Elevator Pitch</h3>
        <hr>
        <p>I’ve spent a lot of time looking into the consulting industry and talking to consultants about their jobs and what it takes to be successful. I believe my interests and skills are a good match for consulting. I have always liked solving problems. My major project during my internship last summer involved creating a questionnaire and conducting dozens of interviews of store operators to develop a best practices manual for franchise owners. I have a 3.7 GPA in Marketing at the University of Northern Colorado’s Monfort College of Business and have done very well in the more analytical courses I’ve taken, including Econometrics and Symbolic Logic. In those classes and others I’ve worked on teams, but I am also a member of the student council and have a good understanding of the importance of working with others to get the job done. I appreciate your willingness to introduce me to Jane Doe at (consulting firm). </p>
            <div class="w3-bar w3-center">
                <i class="material-icons w3-button w3-margin">thumb_up</i> <i class="material-icons w3-button w3-margin">thumb_down</i>
            </div>
    </div>
    <br>
</div>
{% endblock%}

app/templates/category/school.html
{% extends 'base.html'%}

{% block content %}
<div class="w3-container w3-card w3-white w3-margin-bottom" style="height:100%">
    <h3 class="w3-center">School Pitches</h3>
    <div class="w3-panel w3-green w3-card-4 w3-margin w3-padding">
      <h3>Consultation Pitch</h3>
        <hr>
        <p>I’ve spent a lot of time looking into the consulting industry and have reached out and spoken to four different alums in the consulting industry about their jobs and what it takes to be successful. Last semester, I did an independent project writing a business plan for an elder care non-profit that I’d had some exposure to through a neighbor, and the organization has begun to enact several of my recommendations. As this brief background illustrates, I enjoy analyzing key performance drivers, and have pursued academic and extra-curricular opportunities to develop skills in this area. I believe that I am a great fit for your organization and I would appreciate the opportunity to meet with you and learn more about your role at this company and discuss various prospects within the organization.</p>
            <div class="w3-bar w3-center">
                <i class="material-icons w3-button w3-margin">thumb_up</i> <i class="material-icons w3-button w3-margin">thumb_down</i>
            </div>
    </div>

    <div class="w3-panel w3-green w3-card-4 w3-margin w3-padding">
      <h3>Elevator Pitch</h3>
        <hr>
        <p>I’ve spent a lot of time looking into the consulting industry and talking to consultants about their jobs and what it takes to be successful. I believe my interests and skills are a good match for consulting. I have always liked solving problems. My major project during my internship last summer involved creating a questionnaire and conducting dozens of interviews of store operators to develop a best practices manual for franchise owners. I have a 3.7 GPA in Marketing at the University of Northern Colorado’s Monfort College of Business and have done very well in the more analytical courses I’ve taken, including Econometrics and Symbolic Logic. In those classes and others I’ve worked on teams, but I am also a member of the student council and have a good understanding of the importance of working with others to get the job done. I appreciate your willingness to introduce me to Jane Doe at (consulting firm). </p>
            <div class="w3-bar w3-center">
                <i class="material-icons w3-button w3-margin">thumb_up</i> <i class="material-icons w3-button w3-margin">thumb_down</i>
            </div>
    </div>
    <br>
</div>
{% endblock%}

app/templates/index.html
{% extends 'base.html'%}

{% block content %}
<div class="w3-display-container w3-center w3-display-middle w3-card-4 w3-margin w3-green w3-padding" style="color:black; height:40%">

        <h1 > Welcome to Pitch Perfect !!!</h1>
            <hr>
            <br>
        <p >The most efficient way to live your life awaits you...</p>
        <a href="{{url_for('auth.login')}}" class="w3-bar-item w3-button w3-black w3-mobile">Log In</a>

</div>
{% endblock%}

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
{% import "bootstrap/wtf.html" as wtf %}
<head>
    <meta charset="UTF-8">
    {% if title %}
    <title> {{ title }}</title>
    {% else %}
    <title> Pitch Perfect </title>
    {% endif %}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
</head>
<body>
<div class="w3-container"><br><br><br>
<div class="w3-card-4 w3-center" style="width:50%; margin-left:auto; margin-right:auto">
<div class="container w3-margin w3-padding">
{{wtf.quick_form(form)}}<br>
</div>
</div>
</div>
</body>
</html>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}

<!-- Page Container -->
<div class="w3-content " style="max-width:1400px; margin-top:30px">
  <!-- The Grid -->
  <div class="w3-row-padding">
    <!-- Left Column -->
    <div class="w3-third">
      <div class="w3-white w3-text-grey w3-card-4">
        <div class="w3-display-container w3-center">
            {% if user.profile_pic_path %}
            <img class="w3-margin" src="{{url_for('static',filename=user.profile_pic_path)}}" style="max-height:200px; max-width:200px; margin:10px" alt="Avatar">
            {%else%}
            <img src="https://www.theupholsteryforum.com/styles/FLATBOOTS/theme/images/user4.png" style="max-height:200px; max-width:200px" alt="Avatar">
            {% endif %}

        </div>
        <div class="w3-container">
          <h3><i class=" w3-margin-right w3-large w3-text-teal"></i>{{user.username| capitalize}}</h3>
         {% if user.bio %}
          <p><i class="w w3-margin-right w3-large w3-text-teal"></i>{{user.bio}}</p>
            {%else%}
          <p><i class="w w3-margin-right w3-large w3-text-teal"></i>No Bio Yet</p>
            {% endif %}
          <hr>

            {% if user == current_user %}
            <form class="w3-center" action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype ="multipart/form-data">
            <input type="file"  name="photo"  required>
            <input class="w3-bar-item w3-button w3-green" type="submit">

            <a class="w3-button w3-black w3-margin" href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
            {% endif %}
            </form>

            </div>


      </div><br>


    </div>

    <div class="w3-twothird">
        <div class="w3-container w3-card w3-white w3-margin-bottom" style="height:100%">
            <h3 class="w3-center">All Categories</h3>
            <div class="w3-panel w3-green w3-card-4 w3-margin w3-padding">
              <h3>Consultation Pitch</h3>
                <hr>
                <p>I’ve spent a lot of time looking into the consulting industry and have reached out and spoken to four different alums in the consulting industry about their jobs and what it takes to be successful. Last semester, I did an independent project writing a business plan for an elder care non-profit that I’d had some exposure to through a neighbor, and the organization has begun to enact several of my recommendations. As this brief background illustrates, I enjoy analyzing key performance drivers, and have pursued academic and extra-curricular opportunities to develop skills in this area. I believe that I am a great fit for your organization and I would appreciate the opportunity to meet with you and learn more about your role at this company and discuss various prospects within the organization.</p>
            <div class="w3-bar w3-center">
        <i class="material-icons w3-button w3-margin">thumb_up</i> <i class="material-icons w3-button w3-margin">thumb_down</i>
    </div>
            </div>

            <div class="w3-panel w3-green w3-card-4 w3-margin w3-padding">
              <h3>Elevator Pitch</h3>
                <hr>
                <p>I’ve spent a lot of time looking into the consulting industry and talking to consultants about their jobs and what it takes to be successful. I believe my interests and skills are a good match for consulting. I have always liked solving problems. My major project during my internship last summer involved creating a questionnaire and conducting dozens of interviews of store operators to develop a best practices manual for franchise owners. I have a 3.7 GPA in Marketing at the University of Northern Colorado’s Monfort College of Business and have done very well in the more analytical courses I’ve taken, including Econometrics and Symbolic Logic. In those classes and others I’ve worked on teams, but I am also a member of the student council and have a good understanding of the importance of working with others to get the job done. I appreciate your willingness to introduce me to Jane Doe at (consulting firm). </p>
            <div class="w3-bar w3-center">
        <i class="material-icons w3-button w3-margin">thumb_up</i> <i class="material-icons w3-button w3-margin">thumb_down</i>
    </div>
            </div>
            <br>
        </div>
    </div>

  <!-- End Grid -->
  </div>

  <!-- End Page Container -->



{% endblock%}

app/templates/profile/update.html
{% extends 'base.html'%}

{% block content %}
<div class="w3-display-container w3-center w3-display-middle w3-card-4 w3-margin w3-green w3-padding" style="color:black; height:40%">
       {{wtf.quick_form(form)}}
</div>

{% endblock%}